### ISSUE TITLE
sp_ prefix

### ISSUE THREAD

**Issue by patrickjolliffe** [nenadnoveljic/blogs#1]
Nenad,
Not a big issue, and I'm sure it's not affecting the results, but isn't best practice to avoid sp_ prefix in stored procedure?
https://sqlperformance.com/2012/10/t-sql-queries/sp_prefix
In case it's not obvious I'm referring to files like the following:
https://github.com/nenadnoveljic/blogs/blob/master/comparing_TSQL_and_PLSQL_performance/sp_cpu_loop.sql

Regards
Patrick

**Comment by pjolliffe** [comment]
CREATE PROCEDURE [dbo].[sp_cpu_loop] @iterations bigint

**Comment by nenadnoveljic** [comment]
Patrick,

Thank you for the link. Apparently, it's better not to use sp_ prefix for your own procedures.

However, I reran the tests after renaming the procedure, and  it doesn't make any difference in this case.

Best regards,
Nenad
